### ISSUE TITLE
Add new options to add files 

### ISSUE THREAD

**Issue by b1zzu** [b1zzu/scog#2]
Command:
```bash
scog add .bashrc
```

Result:
```yaml
# config.yaml
files:
- file: /home/davide/.bashrc
```
