### ISSUE TITLE
Preserve owner when copying files

### ISSUE THREAD

**Issue by b1zzu** [b1zzu/scog#3]
The owner of a file is annotated in `config.yaml`
```yaml
files:
- file: /home/davide/.bashrc
  owner: davide
```

When an owner is annotated for a directory, all the files and subdirectories should have the same owner.

If it isn't present on the first `pull` of the files the owner will be automatically annotated.

If it is present but the annotated owner is different from the actual owner the `pull` or `push` will fail.

The `add` command should annotate owner.
